### ISSUE TITLE
Repo name change

### ISSUE THREAD

**Issue by nitinkumar30** [Nyandwi/machine_learning_complete#4]
This repository is most likely to be more related to Data Science than whole Machine Learning. So, to be more specific, you may change the repo to ```data_science_complete``` instead of ``machine_learning_complete`` . Thanks !!

**Comment by Nyandwi** [comment]
Thank you for the suggestion. 

I personally think there is no difference between the two as the repo covers most data science topics, but also data science is a very broad term. And the whole emphasis on this repo was all about machine learning. It's fair to leave the name as it is!

**Comment by PritKalariya** [comment]
> Thank you for the suggestion.
> 
> I personally think there is no difference between the two as the repo covers most data science topics, but also data science is a very broad term. And the whole emphasis on this repo was all about machine learning. It's fair to leave the name as it is!

I agree.

**Comment by nitinkumar30** [comment]
> Thank you for the suggestion.
> 
> I personally think there is no difference between the two as the repo covers most data science topics, but also data science is a very broad term. And the whole emphasis on this repo was all about machine learning. It's fair to leave the name as it is!

Sure, I agree to your point @Nyandwi
